apiVersion: v1
kind: Secret
metadata:
  name: passbolt-rustdesk-secret
  namespace: central-platform
type: Opaque
stringData:
  APP_FULL_BASE_URL: "http://passbolt.emiliomoro.local"
  DATASOURCES_DEFAULT_HOST: "postgresql-service"
  DATASOURCES_DEFAULT_USERNAME: "admin"
  DATASOURCES_DEFAULT_PASSWORD: "CHANGE_ME"
  DATASOURCES_DEFAULT_DATABASE: "centraldb"
  EMAIL_DEFAULT_FROM: "admin@yatelomiro.com"
  EMAIL_TRANSPORT_DEFAULT_HOST: "smtp.dondominio.com"
  EMAIL_TRANSPORT_DEFAULT_PORT: "587"
  EMAIL_TRANSPORT_DEFAULT_USERNAME: "admin@yatelomiro.com"
  EMAIL_TRANSPORT_DEFAULT_PASSWORD: "CHANGE_ME"
